stages:
  - test
  - docker_build
  - deploy

rspec:
  stage: test
  image: ruby:2.4.1
  script:
    - bundle install
    - bundle exec rspec --fail-fast -f progress

rubocop:
  stage: test
  image: ruby:2.4.1
  script:
    - bundle install
    - rubocop -F

build_image:
  stage: docker_build
  except:
    - /^feature\/.*$/
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/aisrael/$CI_PROJECT_NAME:latest -t registry.gitlab.com/aisrael/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:8} .
    - docker push registry.gitlab.com/aisrael/$CI_PROJECT_NAME:latest
    - docker push registry.gitlab.com/aisrael/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:8}

tag_tag:
  stage: docker_build
  only:
    - tags
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/aisrael/$CI_PROJECT_NAME:$CI_COMMIT_TAG .
    - docker push registry.gitlab.com/aisrael/$CI_PROJECT_NAME:$CI_COMMIT_TAG

kubectl_set_image:
  stage: deploy
  except:
    - /^feature\/.*$/
  script:
    - kubectl --server="$KUBE_URL" --certificate-authority="$KUBE_CA_PEM_FILE" --token="$KUBE_TOKEN" --namespace="$KUBE_NAMESPACE" \
      set image deployments/tweeter tweeter=registry.gitlab.com/aisrael/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:8}
