stages:
  - test
  - docker_build

rspec:
  stage: test
  image: ruby:2.4.1
  script:
    - bundle install
    - bundle exec rspec --fail-fast -f progress

cucumber:
  stage: test
  image: ruby:2.4.1
  script:
    - bundle install
    - bundle exec cucumber --fail-fast -f progress

rubocop:
  stage: test
  image: ruby:2.4.1
  script:
    - rubocop -F

build_image:
  stage: docker_build
  except:
    - /^feature\/.*$/
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/aisrael/$CI_PROJECT_NAME:latest -t registry.gitlab.com/aisrael/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:8} .
    - docker push registry.gitlab.com/aisrael/$CI_PROJECT_NAME:latest
    - docker push registry.gitlab.com/aisrael/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:8}

tag_tag:
  stage: docker_build
  only:
    - tags
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/aisrael/$CI_PROJECT_NAME:$CI_COMMIT_TAG .
    - docker push registry.gitlab.com/aisrael/$CI_PROJECT_NAME:$CI_COMMIT_TAG
