---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: tweeter
  name: tweeter-mongodb-mongodb
  labels:
    app: tweeter
    db: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweeter
        db: mongo
    spec:
      containers:
      - name: tweeter-mongodb-mongodb
        image: mongo:3.4.4
        ports:
        - name: mongodb
          containerPort: 27017
      #   volumeMounts:
      #   - name: data
      #     mountPath: /data/db
      # volumes:
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: tweeter-mongodb-mongodb
---
apiVersion: v1
kind: Service
metadata:
  namespace: tweeter
  name: tweeter-mongodb-mongodb
  labels:
    app: tweeter
    db: mongo
spec:
  type: ClusterIP
  ports:
  - port: 6379 # the port that the NodePort should serve on
    targetPort: 6379 # the port that the service is serving on
  selector:
    app: tweeter
    db: mongo
  ports:
    - name: mongodb
      port: 27017
